doc-warnings: true
test-warnings: false
strictness: high
max-line-length: 120
pep8:
  full: true
autodetect: true
requirements:
  - requirements.txt
  - requirements-dev.txt
ignore-paths:
  - data
  - docs
  - reports
  - tests
python-targets:
  - 3