language: python
os:
  - linux

python:
  - 2.6
  - 2.7

cache:
  pip: true

before_install:
  - python --version
  - uname -a

addons:
  apt:
    packages:
      - pandoc

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install mock
  - pip install unittest2
  - pip install pypandoc
  - pip install coveralls
notifications:
  email:
    on_success: never
    on_failure: email

script:
  - coverage run --source=src/ setup.py test
after_script:
  - coverage report
after_success:
    coveralls