language: python

os:
  - linux
  - osx

python:
  - 2.6
  - 2.7

cache:
  pip: true

before_install:
  - python --version
  - uname -a
addons:
  apt:
    packages:
    # install pandoc for use with pypandoc for converting the README
    - pandoc

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install mock
  - pip install unittest2
  - pip install json2html
  - pip install urllib3
  - pip install tabulate
  - pip install pypandoc
  - pip install coveralls
notifications:
  email:
    on_success: never
    on_failure: email

# change from 'script: python setup.py test' to this
script:
  - coverage run --source=opendoor setup.py test
after_success:
    coveralls