language: python

os:
  - linux
#  - osx

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

cache:
  pip: false

#matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2

before_install:
  - python --version
  - uname -a


install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

notifications:
  email:
    on_success: never
    on_failure: email

script:
  - coverage run --source=src/ setup.py test
after_script:
  - coverage report
after_success:
    coveralls