language: python
python:
  - 2.6
  - 2.7

before_install:
  - python --version
  - uname -a
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
notifications:
  email:
    on_success: never
    on_failure: email

# change from 'script: python setup.py test' to this
script:
  - coverage run --source=opendoor setup.py test
after_success:
    coveralls